#!/usr/bin/env python3

import re
from pathlib import Path

def demo_question_generation():
    """Demonstrate the question generation process with sample output"""
    
    print("Crypto Question Generator - DEMO MODE")
    print("=" * 50)
    
    file_path = "CRYPTO_TOPICS_FOR_QUESTION_HARVESTING.md"
    
    if not Path(file_path).exists():
        print(f"ERROR: File not found: {file_path}")
        return
    
    # Parse topics (showing it works)
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    topic_blocks = re.findall(r'@BEGIN_TOPIC(.*?)@END_TOPIC', content, re.DOTALL)
    print(f"Found {len(topic_blocks)} topic blocks ready for question generation")
    
    # Show sample topic
    for i, block in enumerate(topic_blocks[:1], 1):
        print(f"\n--- Processing Topic {i} ---")
        
        category_match = re.search(r'CATEGORY:\s*(.+)', block)
        topic_id_match = re.search(r'TOPIC_ID:\s*(.+)', block)
        complexity_match = re.search(r'COMPLEXITY:\s*(.+)', block)
        
        content_lines = block.strip().split('\n')
        content_lines = [line.strip() for line in content_lines if not line.startswith('@') and line.strip()]
        
        if content_lines:
            title = content_lines[0].split('.')[1].strip() if '.' in content_lines[0] else content_lines[0]
            
            print(f"Title: {title}")
            print(f"Category: {category_match.group(1) if category_match else 'Unknown'}")
            print(f"Complexity: {complexity_match.group(1) if complexity_match else 'Unknown'}")
            
            # Show sample questions that would be generated
            print(f"\nSample Questions (15 would be generated by AI):")
            sample_questions = [
                f"1. How can {title.lower()} be applied to Bitcoin trading strategies?",
                f"2. What are the key indicators for {title.lower()} in volatile markets?",
                f"3. What risks should traders consider when using {title.lower()}?",
                f"4. How does {title.lower()} differ between bull and bear markets?",
                f"5. What are common mistakes beginners make with {title.lower()}?"
            ]
            
            for question in sample_questions:
                print(f"   {question}")
            
            print(f"... plus 10 more questions tailored to this topic")
    
    print(f"\n{'='*50}")
    print("DEMO COMPLETE")
    print(f"{'='*50}")
    print("\nTo run with API and generate all questions:")
    print("1. Get your API key from: https://openrouter.ai/")
    print("2. Run: python run_generator.py YOUR_API_KEY")
    print("3. Or set environment variable: set OPENROUTER_API_KEY=your_key")
    print("4. Then run: python crypto_question_generator.py")
    print(f"\nExpected output: crypto_questions/ directory with {len(topic_blocks)} text files")
    print(f"Total questions: {len(topic_blocks) * 15} approximately")

if __name__ == "__main__":
    demo_question_generation()
